AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 buckets for Rock Paper Scissors AWS pipeline'

Parameters:
  BucketNamePrefix:
    Type: String
    Default: 'rps-pipeline'
    Description: Prefix for S3 bucket names

  # LambdaFunctionName:
  #   Type: String
  #   Default: 'RPSLambdaFunction'
  #   Description: Name of the Lambda function to trigger on S3 events

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketNamePrefix}-landing-zone'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # NotificationConfiguration:
      #   LambdaConfigurations: # if any file is created in the landing zone, trigger the Lambda function
      #     - Event: 's3:ObjectCreated:*'
      #       Function: !Ref 'LambdaFunctionName'
      #       Filter:
      #         S3Key:
      #           Rules:
      #             - Name: prefix
      #               Value: 'landing-zone/'
  
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowS3ServiceAccess
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - s3:GetObject
              - s3:PutObject
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*
            
          - Sid: AllowGlueJobAccess
            Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*

Outputs:
  S3BucketName:
    Description: Name of the single pipeline S3 bucket
    Value: !Ref S3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'

  ArtifactsPrefix:
    Description: Prefix for storing templates and scripts
    Value: artifacts
    Export:
      Name: !Sub '${AWS::StackName}-ArtifactsPrefix'

  LandingZonePrefix:
    Description: Prefix for incoming files and event triggers
    Value: landing-zone
    Export:
      Name: !Sub '${AWS::StackName}-LandingZonePrefix'

  OutputPrefix:
    Description: Prefix for final output files
    Value: output
    Export:
      Name: !Sub '${AWS::StackName}-OutputPrefix'
